services:
  go_product_api:
    container_name: go_product_api
    restart: on-failure
    build: .
    env_file:
      - app.env
    ports:
      - "3000:3000"
    depends_on:
      - go_product_api_db
  go_product_api_db:
    container_name: go_product_api_db
    image: postgres:17.2-alpine3.21
    restart: on-failure
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  go_product_api_cache:
    container_name: product_api_go_cache
    image: redis:7.4.2-alpine3.21
    restart: on-failure
    env_file:
      - cache.env
    ports:
      - "6379:6379"
    command: sh -c redis-server --requirepass $$REDIS_PASSWORD
    volumes:
      - rdbdata:/redis/data

volumes:
  pgdata: {}
  rdbdata: {}
